// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dag_config.proto

#ifndef PROTOBUF_dag_5fconfig_2eproto__INCLUDED
#define PROTOBUF_dag_5fconfig_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace apollo {
namespace perception {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_dag_5fconfig_2eproto();
void protobuf_AssignDesc_dag_5fconfig_2eproto();
void protobuf_ShutdownFile_dag_5fconfig_2eproto();

class DAGConfig;
class DAGConfig_Subnode;
class DAGConfig_SubnodeConfig;
class DAGConfig_Event;
class DAGConfig_Edge;
class DAGConfig_EdgeConfig;
class DAGConfig_SharedData;
class DAGConfig_SharedDataConfig;

enum DAGConfig_SubnodeType {
  DAGConfig_SubnodeType_SUBNODE_IN = 1,
  DAGConfig_SubnodeType_SUBNODE_OUT = 2,
  DAGConfig_SubnodeType_SUBNODE_NORMAL = 3
};
bool DAGConfig_SubnodeType_IsValid(int value);
const DAGConfig_SubnodeType DAGConfig_SubnodeType_SubnodeType_MIN = DAGConfig_SubnodeType_SUBNODE_IN;
const DAGConfig_SubnodeType DAGConfig_SubnodeType_SubnodeType_MAX = DAGConfig_SubnodeType_SUBNODE_NORMAL;
const int DAGConfig_SubnodeType_SubnodeType_ARRAYSIZE = DAGConfig_SubnodeType_SubnodeType_MAX + 1;

const ::google::protobuf::EnumDescriptor* DAGConfig_SubnodeType_descriptor();
inline const ::std::string& DAGConfig_SubnodeType_Name(DAGConfig_SubnodeType value) {
  return ::google::protobuf::internal::NameOfEnum(
    DAGConfig_SubnodeType_descriptor(), value);
}
inline bool DAGConfig_SubnodeType_Parse(
    const ::std::string& name, DAGConfig_SubnodeType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DAGConfig_SubnodeType>(
    DAGConfig_SubnodeType_descriptor(), name, value);
}
// ===================================================================

class DAGConfig_Subnode : public ::google::protobuf::Message {
 public:
  DAGConfig_Subnode();
  virtual ~DAGConfig_Subnode();

  DAGConfig_Subnode(const DAGConfig_Subnode& from);

  inline DAGConfig_Subnode& operator=(const DAGConfig_Subnode& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DAGConfig_Subnode& default_instance();

  void Swap(DAGConfig_Subnode* other);

  // implements Message ----------------------------------------------

  DAGConfig_Subnode* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DAGConfig_Subnode& from);
  void MergeFrom(const DAGConfig_Subnode& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional string reserve = 3;
  inline bool has_reserve() const;
  inline void clear_reserve();
  static const int kReserveFieldNumber = 3;
  inline const ::std::string& reserve() const;
  inline void set_reserve(const ::std::string& value);
  inline void set_reserve(const char* value);
  inline void set_reserve(const char* value, size_t size);
  inline ::std::string* mutable_reserve();
  inline ::std::string* release_reserve();
  inline void set_allocated_reserve(::std::string* reserve);

  // optional .apollo.perception.DAGConfig.SubnodeType type = 4 [default = SUBNODE_NORMAL];
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 4;
  inline ::apollo::perception::DAGConfig_SubnodeType type() const;
  inline void set_type(::apollo::perception::DAGConfig_SubnodeType value);

  // @@protoc_insertion_point(class_scope:apollo.perception.DAGConfig.Subnode)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_reserve();
  inline void clear_has_reserve();
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::google::protobuf::int32 id_;
  int type_;
  ::std::string* reserve_;
  friend void  protobuf_AddDesc_dag_5fconfig_2eproto();
  friend void protobuf_AssignDesc_dag_5fconfig_2eproto();
  friend void protobuf_ShutdownFile_dag_5fconfig_2eproto();

  void InitAsDefaultInstance();
  static DAGConfig_Subnode* default_instance_;
};
// -------------------------------------------------------------------

class DAGConfig_SubnodeConfig : public ::google::protobuf::Message {
 public:
  DAGConfig_SubnodeConfig();
  virtual ~DAGConfig_SubnodeConfig();

  DAGConfig_SubnodeConfig(const DAGConfig_SubnodeConfig& from);

  inline DAGConfig_SubnodeConfig& operator=(const DAGConfig_SubnodeConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DAGConfig_SubnodeConfig& default_instance();

  void Swap(DAGConfig_SubnodeConfig* other);

  // implements Message ----------------------------------------------

  DAGConfig_SubnodeConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DAGConfig_SubnodeConfig& from);
  void MergeFrom(const DAGConfig_SubnodeConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.perception.DAGConfig.Subnode subnodes = 1;
  inline int subnodes_size() const;
  inline void clear_subnodes();
  static const int kSubnodesFieldNumber = 1;
  inline const ::apollo::perception::DAGConfig_Subnode& subnodes(int index) const;
  inline ::apollo::perception::DAGConfig_Subnode* mutable_subnodes(int index);
  inline ::apollo::perception::DAGConfig_Subnode* add_subnodes();
  inline const ::google::protobuf::RepeatedPtrField< ::apollo::perception::DAGConfig_Subnode >&
      subnodes() const;
  inline ::google::protobuf::RepeatedPtrField< ::apollo::perception::DAGConfig_Subnode >*
      mutable_subnodes();

  // @@protoc_insertion_point(class_scope:apollo.perception.DAGConfig.SubnodeConfig)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::apollo::perception::DAGConfig_Subnode > subnodes_;
  friend void  protobuf_AddDesc_dag_5fconfig_2eproto();
  friend void protobuf_AssignDesc_dag_5fconfig_2eproto();
  friend void protobuf_ShutdownFile_dag_5fconfig_2eproto();

  void InitAsDefaultInstance();
  static DAGConfig_SubnodeConfig* default_instance_;
};
// -------------------------------------------------------------------

class DAGConfig_Event : public ::google::protobuf::Message {
 public:
  DAGConfig_Event();
  virtual ~DAGConfig_Event();

  DAGConfig_Event(const DAGConfig_Event& from);

  inline DAGConfig_Event& operator=(const DAGConfig_Event& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DAGConfig_Event& default_instance();

  void Swap(DAGConfig_Event* other);

  // implements Message ----------------------------------------------

  DAGConfig_Event* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DAGConfig_Event& from);
  void MergeFrom(const DAGConfig_Event& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // optional string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:apollo.perception.DAGConfig.Event)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::google::protobuf::int32 id_;
  friend void  protobuf_AddDesc_dag_5fconfig_2eproto();
  friend void protobuf_AssignDesc_dag_5fconfig_2eproto();
  friend void protobuf_ShutdownFile_dag_5fconfig_2eproto();

  void InitAsDefaultInstance();
  static DAGConfig_Event* default_instance_;
};
// -------------------------------------------------------------------

class DAGConfig_Edge : public ::google::protobuf::Message {
 public:
  DAGConfig_Edge();
  virtual ~DAGConfig_Edge();

  DAGConfig_Edge(const DAGConfig_Edge& from);

  inline DAGConfig_Edge& operator=(const DAGConfig_Edge& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DAGConfig_Edge& default_instance();

  void Swap(DAGConfig_Edge* other);

  // implements Message ----------------------------------------------

  DAGConfig_Edge* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DAGConfig_Edge& from);
  void MergeFrom(const DAGConfig_Edge& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required int32 from_node = 2;
  inline bool has_from_node() const;
  inline void clear_from_node();
  static const int kFromNodeFieldNumber = 2;
  inline ::google::protobuf::int32 from_node() const;
  inline void set_from_node(::google::protobuf::int32 value);

  // required int32 to_node = 3;
  inline bool has_to_node() const;
  inline void clear_to_node();
  static const int kToNodeFieldNumber = 3;
  inline ::google::protobuf::int32 to_node() const;
  inline void set_to_node(::google::protobuf::int32 value);

  // repeated .apollo.perception.DAGConfig.Event events = 4;
  inline int events_size() const;
  inline void clear_events();
  static const int kEventsFieldNumber = 4;
  inline const ::apollo::perception::DAGConfig_Event& events(int index) const;
  inline ::apollo::perception::DAGConfig_Event* mutable_events(int index);
  inline ::apollo::perception::DAGConfig_Event* add_events();
  inline const ::google::protobuf::RepeatedPtrField< ::apollo::perception::DAGConfig_Event >&
      events() const;
  inline ::google::protobuf::RepeatedPtrField< ::apollo::perception::DAGConfig_Event >*
      mutable_events();

  // @@protoc_insertion_point(class_scope:apollo.perception.DAGConfig.Edge)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_from_node();
  inline void clear_has_from_node();
  inline void set_has_to_node();
  inline void clear_has_to_node();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 from_node_;
  ::google::protobuf::RepeatedPtrField< ::apollo::perception::DAGConfig_Event > events_;
  ::google::protobuf::int32 to_node_;
  friend void  protobuf_AddDesc_dag_5fconfig_2eproto();
  friend void protobuf_AssignDesc_dag_5fconfig_2eproto();
  friend void protobuf_ShutdownFile_dag_5fconfig_2eproto();

  void InitAsDefaultInstance();
  static DAGConfig_Edge* default_instance_;
};
// -------------------------------------------------------------------

class DAGConfig_EdgeConfig : public ::google::protobuf::Message {
 public:
  DAGConfig_EdgeConfig();
  virtual ~DAGConfig_EdgeConfig();

  DAGConfig_EdgeConfig(const DAGConfig_EdgeConfig& from);

  inline DAGConfig_EdgeConfig& operator=(const DAGConfig_EdgeConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DAGConfig_EdgeConfig& default_instance();

  void Swap(DAGConfig_EdgeConfig* other);

  // implements Message ----------------------------------------------

  DAGConfig_EdgeConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DAGConfig_EdgeConfig& from);
  void MergeFrom(const DAGConfig_EdgeConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.perception.DAGConfig.Edge edges = 1;
  inline int edges_size() const;
  inline void clear_edges();
  static const int kEdgesFieldNumber = 1;
  inline const ::apollo::perception::DAGConfig_Edge& edges(int index) const;
  inline ::apollo::perception::DAGConfig_Edge* mutable_edges(int index);
  inline ::apollo::perception::DAGConfig_Edge* add_edges();
  inline const ::google::protobuf::RepeatedPtrField< ::apollo::perception::DAGConfig_Edge >&
      edges() const;
  inline ::google::protobuf::RepeatedPtrField< ::apollo::perception::DAGConfig_Edge >*
      mutable_edges();

  // @@protoc_insertion_point(class_scope:apollo.perception.DAGConfig.EdgeConfig)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::apollo::perception::DAGConfig_Edge > edges_;
  friend void  protobuf_AddDesc_dag_5fconfig_2eproto();
  friend void protobuf_AssignDesc_dag_5fconfig_2eproto();
  friend void protobuf_ShutdownFile_dag_5fconfig_2eproto();

  void InitAsDefaultInstance();
  static DAGConfig_EdgeConfig* default_instance_;
};
// -------------------------------------------------------------------

class DAGConfig_SharedData : public ::google::protobuf::Message {
 public:
  DAGConfig_SharedData();
  virtual ~DAGConfig_SharedData();

  DAGConfig_SharedData(const DAGConfig_SharedData& from);

  inline DAGConfig_SharedData& operator=(const DAGConfig_SharedData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DAGConfig_SharedData& default_instance();

  void Swap(DAGConfig_SharedData* other);

  // implements Message ----------------------------------------------

  DAGConfig_SharedData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DAGConfig_SharedData& from);
  void MergeFrom(const DAGConfig_SharedData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:apollo.perception.DAGConfig.SharedData)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::google::protobuf::int32 id_;
  friend void  protobuf_AddDesc_dag_5fconfig_2eproto();
  friend void protobuf_AssignDesc_dag_5fconfig_2eproto();
  friend void protobuf_ShutdownFile_dag_5fconfig_2eproto();

  void InitAsDefaultInstance();
  static DAGConfig_SharedData* default_instance_;
};
// -------------------------------------------------------------------

class DAGConfig_SharedDataConfig : public ::google::protobuf::Message {
 public:
  DAGConfig_SharedDataConfig();
  virtual ~DAGConfig_SharedDataConfig();

  DAGConfig_SharedDataConfig(const DAGConfig_SharedDataConfig& from);

  inline DAGConfig_SharedDataConfig& operator=(const DAGConfig_SharedDataConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DAGConfig_SharedDataConfig& default_instance();

  void Swap(DAGConfig_SharedDataConfig* other);

  // implements Message ----------------------------------------------

  DAGConfig_SharedDataConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DAGConfig_SharedDataConfig& from);
  void MergeFrom(const DAGConfig_SharedDataConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.perception.DAGConfig.SharedData datas = 1;
  inline int datas_size() const;
  inline void clear_datas();
  static const int kDatasFieldNumber = 1;
  inline const ::apollo::perception::DAGConfig_SharedData& datas(int index) const;
  inline ::apollo::perception::DAGConfig_SharedData* mutable_datas(int index);
  inline ::apollo::perception::DAGConfig_SharedData* add_datas();
  inline const ::google::protobuf::RepeatedPtrField< ::apollo::perception::DAGConfig_SharedData >&
      datas() const;
  inline ::google::protobuf::RepeatedPtrField< ::apollo::perception::DAGConfig_SharedData >*
      mutable_datas();

  // @@protoc_insertion_point(class_scope:apollo.perception.DAGConfig.SharedDataConfig)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::apollo::perception::DAGConfig_SharedData > datas_;
  friend void  protobuf_AddDesc_dag_5fconfig_2eproto();
  friend void protobuf_AssignDesc_dag_5fconfig_2eproto();
  friend void protobuf_ShutdownFile_dag_5fconfig_2eproto();

  void InitAsDefaultInstance();
  static DAGConfig_SharedDataConfig* default_instance_;
};
// -------------------------------------------------------------------

class DAGConfig : public ::google::protobuf::Message {
 public:
  DAGConfig();
  virtual ~DAGConfig();

  DAGConfig(const DAGConfig& from);

  inline DAGConfig& operator=(const DAGConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DAGConfig& default_instance();

  void Swap(DAGConfig* other);

  // implements Message ----------------------------------------------

  DAGConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DAGConfig& from);
  void MergeFrom(const DAGConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef DAGConfig_Subnode Subnode;
  typedef DAGConfig_SubnodeConfig SubnodeConfig;
  typedef DAGConfig_Event Event;
  typedef DAGConfig_Edge Edge;
  typedef DAGConfig_EdgeConfig EdgeConfig;
  typedef DAGConfig_SharedData SharedData;
  typedef DAGConfig_SharedDataConfig SharedDataConfig;

  typedef DAGConfig_SubnodeType SubnodeType;
  static const SubnodeType SUBNODE_IN = DAGConfig_SubnodeType_SUBNODE_IN;
  static const SubnodeType SUBNODE_OUT = DAGConfig_SubnodeType_SUBNODE_OUT;
  static const SubnodeType SUBNODE_NORMAL = DAGConfig_SubnodeType_SUBNODE_NORMAL;
  static inline bool SubnodeType_IsValid(int value) {
    return DAGConfig_SubnodeType_IsValid(value);
  }
  static const SubnodeType SubnodeType_MIN =
    DAGConfig_SubnodeType_SubnodeType_MIN;
  static const SubnodeType SubnodeType_MAX =
    DAGConfig_SubnodeType_SubnodeType_MAX;
  static const int SubnodeType_ARRAYSIZE =
    DAGConfig_SubnodeType_SubnodeType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  SubnodeType_descriptor() {
    return DAGConfig_SubnodeType_descriptor();
  }
  static inline const ::std::string& SubnodeType_Name(SubnodeType value) {
    return DAGConfig_SubnodeType_Name(value);
  }
  static inline bool SubnodeType_Parse(const ::std::string& name,
      SubnodeType* value) {
    return DAGConfig_SubnodeType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .apollo.perception.DAGConfig.SubnodeConfig subnode_config = 1;
  inline bool has_subnode_config() const;
  inline void clear_subnode_config();
  static const int kSubnodeConfigFieldNumber = 1;
  inline const ::apollo::perception::DAGConfig_SubnodeConfig& subnode_config() const;
  inline ::apollo::perception::DAGConfig_SubnodeConfig* mutable_subnode_config();
  inline ::apollo::perception::DAGConfig_SubnodeConfig* release_subnode_config();
  inline void set_allocated_subnode_config(::apollo::perception::DAGConfig_SubnodeConfig* subnode_config);

  // required .apollo.perception.DAGConfig.EdgeConfig edge_config = 2;
  inline bool has_edge_config() const;
  inline void clear_edge_config();
  static const int kEdgeConfigFieldNumber = 2;
  inline const ::apollo::perception::DAGConfig_EdgeConfig& edge_config() const;
  inline ::apollo::perception::DAGConfig_EdgeConfig* mutable_edge_config();
  inline ::apollo::perception::DAGConfig_EdgeConfig* release_edge_config();
  inline void set_allocated_edge_config(::apollo::perception::DAGConfig_EdgeConfig* edge_config);

  // required .apollo.perception.DAGConfig.SharedDataConfig data_config = 3;
  inline bool has_data_config() const;
  inline void clear_data_config();
  static const int kDataConfigFieldNumber = 3;
  inline const ::apollo::perception::DAGConfig_SharedDataConfig& data_config() const;
  inline ::apollo::perception::DAGConfig_SharedDataConfig* mutable_data_config();
  inline ::apollo::perception::DAGConfig_SharedDataConfig* release_data_config();
  inline void set_allocated_data_config(::apollo::perception::DAGConfig_SharedDataConfig* data_config);

  // @@protoc_insertion_point(class_scope:apollo.perception.DAGConfig)
 private:
  inline void set_has_subnode_config();
  inline void clear_has_subnode_config();
  inline void set_has_edge_config();
  inline void clear_has_edge_config();
  inline void set_has_data_config();
  inline void clear_has_data_config();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::apollo::perception::DAGConfig_SubnodeConfig* subnode_config_;
  ::apollo::perception::DAGConfig_EdgeConfig* edge_config_;
  ::apollo::perception::DAGConfig_SharedDataConfig* data_config_;
  friend void  protobuf_AddDesc_dag_5fconfig_2eproto();
  friend void protobuf_AssignDesc_dag_5fconfig_2eproto();
  friend void protobuf_ShutdownFile_dag_5fconfig_2eproto();

  void InitAsDefaultInstance();
  static DAGConfig* default_instance_;
};
// ===================================================================


// ===================================================================

// DAGConfig_Subnode

// required int32 id = 1;
inline bool DAGConfig_Subnode::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DAGConfig_Subnode::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DAGConfig_Subnode::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DAGConfig_Subnode::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 DAGConfig_Subnode::id() const {
  // @@protoc_insertion_point(field_get:apollo.perception.DAGConfig.Subnode.id)
  return id_;
}
inline void DAGConfig_Subnode::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.DAGConfig.Subnode.id)
}

// required string name = 2;
inline bool DAGConfig_Subnode::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DAGConfig_Subnode::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DAGConfig_Subnode::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DAGConfig_Subnode::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& DAGConfig_Subnode::name() const {
  // @@protoc_insertion_point(field_get:apollo.perception.DAGConfig.Subnode.name)
  return *name_;
}
inline void DAGConfig_Subnode::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:apollo.perception.DAGConfig.Subnode.name)
}
inline void DAGConfig_Subnode::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:apollo.perception.DAGConfig.Subnode.name)
}
inline void DAGConfig_Subnode::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:apollo.perception.DAGConfig.Subnode.name)
}
inline ::std::string* DAGConfig_Subnode::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:apollo.perception.DAGConfig.Subnode.name)
  return name_;
}
inline ::std::string* DAGConfig_Subnode::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void DAGConfig_Subnode::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.DAGConfig.Subnode.name)
}

// optional string reserve = 3;
inline bool DAGConfig_Subnode::has_reserve() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DAGConfig_Subnode::set_has_reserve() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DAGConfig_Subnode::clear_has_reserve() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DAGConfig_Subnode::clear_reserve() {
  if (reserve_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    reserve_->clear();
  }
  clear_has_reserve();
}
inline const ::std::string& DAGConfig_Subnode::reserve() const {
  // @@protoc_insertion_point(field_get:apollo.perception.DAGConfig.Subnode.reserve)
  return *reserve_;
}
inline void DAGConfig_Subnode::set_reserve(const ::std::string& value) {
  set_has_reserve();
  if (reserve_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    reserve_ = new ::std::string;
  }
  reserve_->assign(value);
  // @@protoc_insertion_point(field_set:apollo.perception.DAGConfig.Subnode.reserve)
}
inline void DAGConfig_Subnode::set_reserve(const char* value) {
  set_has_reserve();
  if (reserve_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    reserve_ = new ::std::string;
  }
  reserve_->assign(value);
  // @@protoc_insertion_point(field_set_char:apollo.perception.DAGConfig.Subnode.reserve)
}
inline void DAGConfig_Subnode::set_reserve(const char* value, size_t size) {
  set_has_reserve();
  if (reserve_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    reserve_ = new ::std::string;
  }
  reserve_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:apollo.perception.DAGConfig.Subnode.reserve)
}
inline ::std::string* DAGConfig_Subnode::mutable_reserve() {
  set_has_reserve();
  if (reserve_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    reserve_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:apollo.perception.DAGConfig.Subnode.reserve)
  return reserve_;
}
inline ::std::string* DAGConfig_Subnode::release_reserve() {
  clear_has_reserve();
  if (reserve_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = reserve_;
    reserve_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void DAGConfig_Subnode::set_allocated_reserve(::std::string* reserve) {
  if (reserve_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete reserve_;
  }
  if (reserve) {
    set_has_reserve();
    reserve_ = reserve;
  } else {
    clear_has_reserve();
    reserve_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.DAGConfig.Subnode.reserve)
}

// optional .apollo.perception.DAGConfig.SubnodeType type = 4 [default = SUBNODE_NORMAL];
inline bool DAGConfig_Subnode::has_type() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void DAGConfig_Subnode::set_has_type() {
  _has_bits_[0] |= 0x00000008u;
}
inline void DAGConfig_Subnode::clear_has_type() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void DAGConfig_Subnode::clear_type() {
  type_ = 3;
  clear_has_type();
}
inline ::apollo::perception::DAGConfig_SubnodeType DAGConfig_Subnode::type() const {
  // @@protoc_insertion_point(field_get:apollo.perception.DAGConfig.Subnode.type)
  return static_cast< ::apollo::perception::DAGConfig_SubnodeType >(type_);
}
inline void DAGConfig_Subnode::set_type(::apollo::perception::DAGConfig_SubnodeType value) {
  assert(::apollo::perception::DAGConfig_SubnodeType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.DAGConfig.Subnode.type)
}

// -------------------------------------------------------------------

// DAGConfig_SubnodeConfig

// repeated .apollo.perception.DAGConfig.Subnode subnodes = 1;
inline int DAGConfig_SubnodeConfig::subnodes_size() const {
  return subnodes_.size();
}
inline void DAGConfig_SubnodeConfig::clear_subnodes() {
  subnodes_.Clear();
}
inline const ::apollo::perception::DAGConfig_Subnode& DAGConfig_SubnodeConfig::subnodes(int index) const {
  // @@protoc_insertion_point(field_get:apollo.perception.DAGConfig.SubnodeConfig.subnodes)
  return subnodes_.Get(index);
}
inline ::apollo::perception::DAGConfig_Subnode* DAGConfig_SubnodeConfig::mutable_subnodes(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.perception.DAGConfig.SubnodeConfig.subnodes)
  return subnodes_.Mutable(index);
}
inline ::apollo::perception::DAGConfig_Subnode* DAGConfig_SubnodeConfig::add_subnodes() {
  // @@protoc_insertion_point(field_add:apollo.perception.DAGConfig.SubnodeConfig.subnodes)
  return subnodes_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::perception::DAGConfig_Subnode >&
DAGConfig_SubnodeConfig::subnodes() const {
  // @@protoc_insertion_point(field_list:apollo.perception.DAGConfig.SubnodeConfig.subnodes)
  return subnodes_;
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::perception::DAGConfig_Subnode >*
DAGConfig_SubnodeConfig::mutable_subnodes() {
  // @@protoc_insertion_point(field_mutable_list:apollo.perception.DAGConfig.SubnodeConfig.subnodes)
  return &subnodes_;
}

// -------------------------------------------------------------------

// DAGConfig_Event

// required int32 id = 1;
inline bool DAGConfig_Event::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DAGConfig_Event::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DAGConfig_Event::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DAGConfig_Event::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 DAGConfig_Event::id() const {
  // @@protoc_insertion_point(field_get:apollo.perception.DAGConfig.Event.id)
  return id_;
}
inline void DAGConfig_Event::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.DAGConfig.Event.id)
}

// optional string name = 2;
inline bool DAGConfig_Event::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DAGConfig_Event::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DAGConfig_Event::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DAGConfig_Event::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& DAGConfig_Event::name() const {
  // @@protoc_insertion_point(field_get:apollo.perception.DAGConfig.Event.name)
  return *name_;
}
inline void DAGConfig_Event::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:apollo.perception.DAGConfig.Event.name)
}
inline void DAGConfig_Event::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:apollo.perception.DAGConfig.Event.name)
}
inline void DAGConfig_Event::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:apollo.perception.DAGConfig.Event.name)
}
inline ::std::string* DAGConfig_Event::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:apollo.perception.DAGConfig.Event.name)
  return name_;
}
inline ::std::string* DAGConfig_Event::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void DAGConfig_Event::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.DAGConfig.Event.name)
}

// -------------------------------------------------------------------

// DAGConfig_Edge

// required int32 id = 1;
inline bool DAGConfig_Edge::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DAGConfig_Edge::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DAGConfig_Edge::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DAGConfig_Edge::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 DAGConfig_Edge::id() const {
  // @@protoc_insertion_point(field_get:apollo.perception.DAGConfig.Edge.id)
  return id_;
}
inline void DAGConfig_Edge::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.DAGConfig.Edge.id)
}

// required int32 from_node = 2;
inline bool DAGConfig_Edge::has_from_node() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DAGConfig_Edge::set_has_from_node() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DAGConfig_Edge::clear_has_from_node() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DAGConfig_Edge::clear_from_node() {
  from_node_ = 0;
  clear_has_from_node();
}
inline ::google::protobuf::int32 DAGConfig_Edge::from_node() const {
  // @@protoc_insertion_point(field_get:apollo.perception.DAGConfig.Edge.from_node)
  return from_node_;
}
inline void DAGConfig_Edge::set_from_node(::google::protobuf::int32 value) {
  set_has_from_node();
  from_node_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.DAGConfig.Edge.from_node)
}

// required int32 to_node = 3;
inline bool DAGConfig_Edge::has_to_node() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DAGConfig_Edge::set_has_to_node() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DAGConfig_Edge::clear_has_to_node() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DAGConfig_Edge::clear_to_node() {
  to_node_ = 0;
  clear_has_to_node();
}
inline ::google::protobuf::int32 DAGConfig_Edge::to_node() const {
  // @@protoc_insertion_point(field_get:apollo.perception.DAGConfig.Edge.to_node)
  return to_node_;
}
inline void DAGConfig_Edge::set_to_node(::google::protobuf::int32 value) {
  set_has_to_node();
  to_node_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.DAGConfig.Edge.to_node)
}

// repeated .apollo.perception.DAGConfig.Event events = 4;
inline int DAGConfig_Edge::events_size() const {
  return events_.size();
}
inline void DAGConfig_Edge::clear_events() {
  events_.Clear();
}
inline const ::apollo::perception::DAGConfig_Event& DAGConfig_Edge::events(int index) const {
  // @@protoc_insertion_point(field_get:apollo.perception.DAGConfig.Edge.events)
  return events_.Get(index);
}
inline ::apollo::perception::DAGConfig_Event* DAGConfig_Edge::mutable_events(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.perception.DAGConfig.Edge.events)
  return events_.Mutable(index);
}
inline ::apollo::perception::DAGConfig_Event* DAGConfig_Edge::add_events() {
  // @@protoc_insertion_point(field_add:apollo.perception.DAGConfig.Edge.events)
  return events_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::perception::DAGConfig_Event >&
DAGConfig_Edge::events() const {
  // @@protoc_insertion_point(field_list:apollo.perception.DAGConfig.Edge.events)
  return events_;
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::perception::DAGConfig_Event >*
DAGConfig_Edge::mutable_events() {
  // @@protoc_insertion_point(field_mutable_list:apollo.perception.DAGConfig.Edge.events)
  return &events_;
}

// -------------------------------------------------------------------

// DAGConfig_EdgeConfig

// repeated .apollo.perception.DAGConfig.Edge edges = 1;
inline int DAGConfig_EdgeConfig::edges_size() const {
  return edges_.size();
}
inline void DAGConfig_EdgeConfig::clear_edges() {
  edges_.Clear();
}
inline const ::apollo::perception::DAGConfig_Edge& DAGConfig_EdgeConfig::edges(int index) const {
  // @@protoc_insertion_point(field_get:apollo.perception.DAGConfig.EdgeConfig.edges)
  return edges_.Get(index);
}
inline ::apollo::perception::DAGConfig_Edge* DAGConfig_EdgeConfig::mutable_edges(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.perception.DAGConfig.EdgeConfig.edges)
  return edges_.Mutable(index);
}
inline ::apollo::perception::DAGConfig_Edge* DAGConfig_EdgeConfig::add_edges() {
  // @@protoc_insertion_point(field_add:apollo.perception.DAGConfig.EdgeConfig.edges)
  return edges_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::perception::DAGConfig_Edge >&
DAGConfig_EdgeConfig::edges() const {
  // @@protoc_insertion_point(field_list:apollo.perception.DAGConfig.EdgeConfig.edges)
  return edges_;
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::perception::DAGConfig_Edge >*
DAGConfig_EdgeConfig::mutable_edges() {
  // @@protoc_insertion_point(field_mutable_list:apollo.perception.DAGConfig.EdgeConfig.edges)
  return &edges_;
}

// -------------------------------------------------------------------

// DAGConfig_SharedData

// required int32 id = 1;
inline bool DAGConfig_SharedData::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DAGConfig_SharedData::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DAGConfig_SharedData::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DAGConfig_SharedData::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 DAGConfig_SharedData::id() const {
  // @@protoc_insertion_point(field_get:apollo.perception.DAGConfig.SharedData.id)
  return id_;
}
inline void DAGConfig_SharedData::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.DAGConfig.SharedData.id)
}

// required string name = 2;
inline bool DAGConfig_SharedData::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DAGConfig_SharedData::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DAGConfig_SharedData::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DAGConfig_SharedData::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& DAGConfig_SharedData::name() const {
  // @@protoc_insertion_point(field_get:apollo.perception.DAGConfig.SharedData.name)
  return *name_;
}
inline void DAGConfig_SharedData::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:apollo.perception.DAGConfig.SharedData.name)
}
inline void DAGConfig_SharedData::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:apollo.perception.DAGConfig.SharedData.name)
}
inline void DAGConfig_SharedData::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:apollo.perception.DAGConfig.SharedData.name)
}
inline ::std::string* DAGConfig_SharedData::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:apollo.perception.DAGConfig.SharedData.name)
  return name_;
}
inline ::std::string* DAGConfig_SharedData::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void DAGConfig_SharedData::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.DAGConfig.SharedData.name)
}

// -------------------------------------------------------------------

// DAGConfig_SharedDataConfig

// repeated .apollo.perception.DAGConfig.SharedData datas = 1;
inline int DAGConfig_SharedDataConfig::datas_size() const {
  return datas_.size();
}
inline void DAGConfig_SharedDataConfig::clear_datas() {
  datas_.Clear();
}
inline const ::apollo::perception::DAGConfig_SharedData& DAGConfig_SharedDataConfig::datas(int index) const {
  // @@protoc_insertion_point(field_get:apollo.perception.DAGConfig.SharedDataConfig.datas)
  return datas_.Get(index);
}
inline ::apollo::perception::DAGConfig_SharedData* DAGConfig_SharedDataConfig::mutable_datas(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.perception.DAGConfig.SharedDataConfig.datas)
  return datas_.Mutable(index);
}
inline ::apollo::perception::DAGConfig_SharedData* DAGConfig_SharedDataConfig::add_datas() {
  // @@protoc_insertion_point(field_add:apollo.perception.DAGConfig.SharedDataConfig.datas)
  return datas_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::perception::DAGConfig_SharedData >&
DAGConfig_SharedDataConfig::datas() const {
  // @@protoc_insertion_point(field_list:apollo.perception.DAGConfig.SharedDataConfig.datas)
  return datas_;
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::perception::DAGConfig_SharedData >*
DAGConfig_SharedDataConfig::mutable_datas() {
  // @@protoc_insertion_point(field_mutable_list:apollo.perception.DAGConfig.SharedDataConfig.datas)
  return &datas_;
}

// -------------------------------------------------------------------

// DAGConfig

// required .apollo.perception.DAGConfig.SubnodeConfig subnode_config = 1;
inline bool DAGConfig::has_subnode_config() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DAGConfig::set_has_subnode_config() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DAGConfig::clear_has_subnode_config() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DAGConfig::clear_subnode_config() {
  if (subnode_config_ != NULL) subnode_config_->::apollo::perception::DAGConfig_SubnodeConfig::Clear();
  clear_has_subnode_config();
}
inline const ::apollo::perception::DAGConfig_SubnodeConfig& DAGConfig::subnode_config() const {
  // @@protoc_insertion_point(field_get:apollo.perception.DAGConfig.subnode_config)
  return subnode_config_ != NULL ? *subnode_config_ : *default_instance_->subnode_config_;
}
inline ::apollo::perception::DAGConfig_SubnodeConfig* DAGConfig::mutable_subnode_config() {
  set_has_subnode_config();
  if (subnode_config_ == NULL) subnode_config_ = new ::apollo::perception::DAGConfig_SubnodeConfig;
  // @@protoc_insertion_point(field_mutable:apollo.perception.DAGConfig.subnode_config)
  return subnode_config_;
}
inline ::apollo::perception::DAGConfig_SubnodeConfig* DAGConfig::release_subnode_config() {
  clear_has_subnode_config();
  ::apollo::perception::DAGConfig_SubnodeConfig* temp = subnode_config_;
  subnode_config_ = NULL;
  return temp;
}
inline void DAGConfig::set_allocated_subnode_config(::apollo::perception::DAGConfig_SubnodeConfig* subnode_config) {
  delete subnode_config_;
  subnode_config_ = subnode_config;
  if (subnode_config) {
    set_has_subnode_config();
  } else {
    clear_has_subnode_config();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.DAGConfig.subnode_config)
}

// required .apollo.perception.DAGConfig.EdgeConfig edge_config = 2;
inline bool DAGConfig::has_edge_config() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DAGConfig::set_has_edge_config() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DAGConfig::clear_has_edge_config() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DAGConfig::clear_edge_config() {
  if (edge_config_ != NULL) edge_config_->::apollo::perception::DAGConfig_EdgeConfig::Clear();
  clear_has_edge_config();
}
inline const ::apollo::perception::DAGConfig_EdgeConfig& DAGConfig::edge_config() const {
  // @@protoc_insertion_point(field_get:apollo.perception.DAGConfig.edge_config)
  return edge_config_ != NULL ? *edge_config_ : *default_instance_->edge_config_;
}
inline ::apollo::perception::DAGConfig_EdgeConfig* DAGConfig::mutable_edge_config() {
  set_has_edge_config();
  if (edge_config_ == NULL) edge_config_ = new ::apollo::perception::DAGConfig_EdgeConfig;
  // @@protoc_insertion_point(field_mutable:apollo.perception.DAGConfig.edge_config)
  return edge_config_;
}
inline ::apollo::perception::DAGConfig_EdgeConfig* DAGConfig::release_edge_config() {
  clear_has_edge_config();
  ::apollo::perception::DAGConfig_EdgeConfig* temp = edge_config_;
  edge_config_ = NULL;
  return temp;
}
inline void DAGConfig::set_allocated_edge_config(::apollo::perception::DAGConfig_EdgeConfig* edge_config) {
  delete edge_config_;
  edge_config_ = edge_config;
  if (edge_config) {
    set_has_edge_config();
  } else {
    clear_has_edge_config();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.DAGConfig.edge_config)
}

// required .apollo.perception.DAGConfig.SharedDataConfig data_config = 3;
inline bool DAGConfig::has_data_config() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DAGConfig::set_has_data_config() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DAGConfig::clear_has_data_config() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DAGConfig::clear_data_config() {
  if (data_config_ != NULL) data_config_->::apollo::perception::DAGConfig_SharedDataConfig::Clear();
  clear_has_data_config();
}
inline const ::apollo::perception::DAGConfig_SharedDataConfig& DAGConfig::data_config() const {
  // @@protoc_insertion_point(field_get:apollo.perception.DAGConfig.data_config)
  return data_config_ != NULL ? *data_config_ : *default_instance_->data_config_;
}
inline ::apollo::perception::DAGConfig_SharedDataConfig* DAGConfig::mutable_data_config() {
  set_has_data_config();
  if (data_config_ == NULL) data_config_ = new ::apollo::perception::DAGConfig_SharedDataConfig;
  // @@protoc_insertion_point(field_mutable:apollo.perception.DAGConfig.data_config)
  return data_config_;
}
inline ::apollo::perception::DAGConfig_SharedDataConfig* DAGConfig::release_data_config() {
  clear_has_data_config();
  ::apollo::perception::DAGConfig_SharedDataConfig* temp = data_config_;
  data_config_ = NULL;
  return temp;
}
inline void DAGConfig::set_allocated_data_config(::apollo::perception::DAGConfig_SharedDataConfig* data_config) {
  delete data_config_;
  data_config_ = data_config;
  if (data_config) {
    set_has_data_config();
  } else {
    clear_has_data_config();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.DAGConfig.data_config)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace perception
}  // namespace apollo

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::apollo::perception::DAGConfig_SubnodeType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::perception::DAGConfig_SubnodeType>() {
  return ::apollo::perception::DAGConfig_SubnodeType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dag_5fconfig_2eproto__INCLUDED
