// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dag_config.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "dag_config.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace apollo {
namespace perception {

namespace {

const ::google::protobuf::Descriptor* DAGConfig_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DAGConfig_reflection_ = NULL;
const ::google::protobuf::Descriptor* DAGConfig_Subnode_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DAGConfig_Subnode_reflection_ = NULL;
const ::google::protobuf::Descriptor* DAGConfig_SubnodeConfig_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DAGConfig_SubnodeConfig_reflection_ = NULL;
const ::google::protobuf::Descriptor* DAGConfig_Event_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DAGConfig_Event_reflection_ = NULL;
const ::google::protobuf::Descriptor* DAGConfig_Edge_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DAGConfig_Edge_reflection_ = NULL;
const ::google::protobuf::Descriptor* DAGConfig_EdgeConfig_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DAGConfig_EdgeConfig_reflection_ = NULL;
const ::google::protobuf::Descriptor* DAGConfig_SharedData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DAGConfig_SharedData_reflection_ = NULL;
const ::google::protobuf::Descriptor* DAGConfig_SharedDataConfig_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DAGConfig_SharedDataConfig_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* DAGConfig_SubnodeType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_dag_5fconfig_2eproto() {
  protobuf_AddDesc_dag_5fconfig_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "dag_config.proto");
  GOOGLE_CHECK(file != NULL);
  DAGConfig_descriptor_ = file->message_type(0);
  static const int DAGConfig_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig, subnode_config_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig, edge_config_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig, data_config_),
  };
  DAGConfig_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DAGConfig_descriptor_,
      DAGConfig::default_instance_,
      DAGConfig_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DAGConfig));
  DAGConfig_Subnode_descriptor_ = DAGConfig_descriptor_->nested_type(0);
  static const int DAGConfig_Subnode_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_Subnode, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_Subnode, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_Subnode, reserve_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_Subnode, type_),
  };
  DAGConfig_Subnode_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DAGConfig_Subnode_descriptor_,
      DAGConfig_Subnode::default_instance_,
      DAGConfig_Subnode_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_Subnode, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_Subnode, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DAGConfig_Subnode));
  DAGConfig_SubnodeConfig_descriptor_ = DAGConfig_descriptor_->nested_type(1);
  static const int DAGConfig_SubnodeConfig_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_SubnodeConfig, subnodes_),
  };
  DAGConfig_SubnodeConfig_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DAGConfig_SubnodeConfig_descriptor_,
      DAGConfig_SubnodeConfig::default_instance_,
      DAGConfig_SubnodeConfig_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_SubnodeConfig, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_SubnodeConfig, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DAGConfig_SubnodeConfig));
  DAGConfig_Event_descriptor_ = DAGConfig_descriptor_->nested_type(2);
  static const int DAGConfig_Event_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_Event, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_Event, name_),
  };
  DAGConfig_Event_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DAGConfig_Event_descriptor_,
      DAGConfig_Event::default_instance_,
      DAGConfig_Event_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_Event, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_Event, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DAGConfig_Event));
  DAGConfig_Edge_descriptor_ = DAGConfig_descriptor_->nested_type(3);
  static const int DAGConfig_Edge_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_Edge, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_Edge, from_node_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_Edge, to_node_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_Edge, events_),
  };
  DAGConfig_Edge_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DAGConfig_Edge_descriptor_,
      DAGConfig_Edge::default_instance_,
      DAGConfig_Edge_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_Edge, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_Edge, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DAGConfig_Edge));
  DAGConfig_EdgeConfig_descriptor_ = DAGConfig_descriptor_->nested_type(4);
  static const int DAGConfig_EdgeConfig_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_EdgeConfig, edges_),
  };
  DAGConfig_EdgeConfig_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DAGConfig_EdgeConfig_descriptor_,
      DAGConfig_EdgeConfig::default_instance_,
      DAGConfig_EdgeConfig_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_EdgeConfig, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_EdgeConfig, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DAGConfig_EdgeConfig));
  DAGConfig_SharedData_descriptor_ = DAGConfig_descriptor_->nested_type(5);
  static const int DAGConfig_SharedData_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_SharedData, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_SharedData, name_),
  };
  DAGConfig_SharedData_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DAGConfig_SharedData_descriptor_,
      DAGConfig_SharedData::default_instance_,
      DAGConfig_SharedData_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_SharedData, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_SharedData, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DAGConfig_SharedData));
  DAGConfig_SharedDataConfig_descriptor_ = DAGConfig_descriptor_->nested_type(6);
  static const int DAGConfig_SharedDataConfig_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_SharedDataConfig, datas_),
  };
  DAGConfig_SharedDataConfig_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DAGConfig_SharedDataConfig_descriptor_,
      DAGConfig_SharedDataConfig::default_instance_,
      DAGConfig_SharedDataConfig_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_SharedDataConfig, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DAGConfig_SharedDataConfig, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DAGConfig_SharedDataConfig));
  DAGConfig_SubnodeType_descriptor_ = DAGConfig_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_dag_5fconfig_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DAGConfig_descriptor_, &DAGConfig::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DAGConfig_Subnode_descriptor_, &DAGConfig_Subnode::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DAGConfig_SubnodeConfig_descriptor_, &DAGConfig_SubnodeConfig::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DAGConfig_Event_descriptor_, &DAGConfig_Event::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DAGConfig_Edge_descriptor_, &DAGConfig_Edge::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DAGConfig_EdgeConfig_descriptor_, &DAGConfig_EdgeConfig::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DAGConfig_SharedData_descriptor_, &DAGConfig_SharedData::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DAGConfig_SharedDataConfig_descriptor_, &DAGConfig_SharedDataConfig::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_dag_5fconfig_2eproto() {
  delete DAGConfig::default_instance_;
  delete DAGConfig_reflection_;
  delete DAGConfig_Subnode::default_instance_;
  delete DAGConfig_Subnode_reflection_;
  delete DAGConfig_SubnodeConfig::default_instance_;
  delete DAGConfig_SubnodeConfig_reflection_;
  delete DAGConfig_Event::default_instance_;
  delete DAGConfig_Event_reflection_;
  delete DAGConfig_Edge::default_instance_;
  delete DAGConfig_Edge_reflection_;
  delete DAGConfig_EdgeConfig::default_instance_;
  delete DAGConfig_EdgeConfig_reflection_;
  delete DAGConfig_SharedData::default_instance_;
  delete DAGConfig_SharedData_reflection_;
  delete DAGConfig_SharedDataConfig::default_instance_;
  delete DAGConfig_SharedDataConfig_reflection_;
}

void protobuf_AddDesc_dag_5fconfig_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020dag_config.proto\022\021apollo.perception\"\237\006"
    "\n\tDAGConfig\022B\n\016subnode_config\030\001 \002(\0132*.ap"
    "ollo.perception.DAGConfig.SubnodeConfig\022"
    "<\n\013edge_config\030\002 \002(\0132\'.apollo.perception"
    ".DAGConfig.EdgeConfig\022B\n\013data_config\030\003 \002"
    "(\0132-.apollo.perception.DAGConfig.SharedD"
    "ataConfig\032|\n\007Subnode\022\n\n\002id\030\001 \002(\005\022\014\n\004name"
    "\030\002 \002(\t\022\017\n\007reserve\030\003 \001(\t\022F\n\004type\030\004 \001(\0162(."
    "apollo.perception.DAGConfig.SubnodeType:"
    "\016SUBNODE_NORMAL\032G\n\rSubnodeConfig\0226\n\010subn"
    "odes\030\001 \003(\0132$.apollo.perception.DAGConfig"
    ".Subnode\032!\n\005Event\022\n\n\002id\030\001 \002(\005\022\014\n\004name\030\002 "
    "\001(\t\032j\n\004Edge\022\n\n\002id\030\001 \002(\005\022\021\n\tfrom_node\030\002 \002"
    "(\005\022\017\n\007to_node\030\003 \002(\005\0222\n\006events\030\004 \003(\0132\".ap"
    "ollo.perception.DAGConfig.Event\032>\n\nEdgeC"
    "onfig\0220\n\005edges\030\001 \003(\0132!.apollo.perception"
    ".DAGConfig.Edge\032&\n\nSharedData\022\n\n\002id\030\001 \002("
    "\005\022\014\n\004name\030\002 \002(\t\032J\n\020SharedDataConfig\0226\n\005d"
    "atas\030\001 \003(\0132\'.apollo.perception.DAGConfig"
    ".SharedData\"B\n\013SubnodeType\022\016\n\nSUBNODE_IN"
    "\020\001\022\017\n\013SUBNODE_OUT\020\002\022\022\n\016SUBNODE_NORMAL\020\003", 839);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "dag_config.proto", &protobuf_RegisterTypes);
  DAGConfig::default_instance_ = new DAGConfig();
  DAGConfig_Subnode::default_instance_ = new DAGConfig_Subnode();
  DAGConfig_SubnodeConfig::default_instance_ = new DAGConfig_SubnodeConfig();
  DAGConfig_Event::default_instance_ = new DAGConfig_Event();
  DAGConfig_Edge::default_instance_ = new DAGConfig_Edge();
  DAGConfig_EdgeConfig::default_instance_ = new DAGConfig_EdgeConfig();
  DAGConfig_SharedData::default_instance_ = new DAGConfig_SharedData();
  DAGConfig_SharedDataConfig::default_instance_ = new DAGConfig_SharedDataConfig();
  DAGConfig::default_instance_->InitAsDefaultInstance();
  DAGConfig_Subnode::default_instance_->InitAsDefaultInstance();
  DAGConfig_SubnodeConfig::default_instance_->InitAsDefaultInstance();
  DAGConfig_Event::default_instance_->InitAsDefaultInstance();
  DAGConfig_Edge::default_instance_->InitAsDefaultInstance();
  DAGConfig_EdgeConfig::default_instance_->InitAsDefaultInstance();
  DAGConfig_SharedData::default_instance_->InitAsDefaultInstance();
  DAGConfig_SharedDataConfig::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_dag_5fconfig_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_dag_5fconfig_2eproto {
  StaticDescriptorInitializer_dag_5fconfig_2eproto() {
    protobuf_AddDesc_dag_5fconfig_2eproto();
  }
} static_descriptor_initializer_dag_5fconfig_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* DAGConfig_SubnodeType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DAGConfig_SubnodeType_descriptor_;
}
bool DAGConfig_SubnodeType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const DAGConfig_SubnodeType DAGConfig::SUBNODE_IN;
const DAGConfig_SubnodeType DAGConfig::SUBNODE_OUT;
const DAGConfig_SubnodeType DAGConfig::SUBNODE_NORMAL;
const DAGConfig_SubnodeType DAGConfig::SubnodeType_MIN;
const DAGConfig_SubnodeType DAGConfig::SubnodeType_MAX;
const int DAGConfig::SubnodeType_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int DAGConfig_Subnode::kIdFieldNumber;
const int DAGConfig_Subnode::kNameFieldNumber;
const int DAGConfig_Subnode::kReserveFieldNumber;
const int DAGConfig_Subnode::kTypeFieldNumber;
#endif  // !_MSC_VER

DAGConfig_Subnode::DAGConfig_Subnode()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.perception.DAGConfig.Subnode)
}

void DAGConfig_Subnode::InitAsDefaultInstance() {
}

DAGConfig_Subnode::DAGConfig_Subnode(const DAGConfig_Subnode& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:apollo.perception.DAGConfig.Subnode)
}

void DAGConfig_Subnode::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reserve_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  type_ = 3;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DAGConfig_Subnode::~DAGConfig_Subnode() {
  // @@protoc_insertion_point(destructor:apollo.perception.DAGConfig.Subnode)
  SharedDtor();
}

void DAGConfig_Subnode::SharedDtor() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (reserve_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete reserve_;
  }
  if (this != default_instance_) {
  }
}

void DAGConfig_Subnode::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DAGConfig_Subnode::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DAGConfig_Subnode_descriptor_;
}

const DAGConfig_Subnode& DAGConfig_Subnode::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dag_5fconfig_2eproto();
  return *default_instance_;
}

DAGConfig_Subnode* DAGConfig_Subnode::default_instance_ = NULL;

DAGConfig_Subnode* DAGConfig_Subnode::New() const {
  return new DAGConfig_Subnode;
}

void DAGConfig_Subnode::Clear() {
  if (_has_bits_[0 / 32] & 15) {
    id_ = 0;
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        name_->clear();
      }
    }
    if (has_reserve()) {
      if (reserve_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        reserve_->clear();
      }
    }
    type_ = 3;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DAGConfig_Subnode::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.perception.DAGConfig.Subnode)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_name;
        break;
      }

      // required string name = 2;
      case 2: {
        if (tag == 18) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_reserve;
        break;
      }

      // optional string reserve = 3;
      case 3: {
        if (tag == 26) {
         parse_reserve:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_reserve()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->reserve().data(), this->reserve().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "reserve");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_type;
        break;
      }

      // optional .apollo.perception.DAGConfig.SubnodeType type = 4 [default = SUBNODE_NORMAL];
      case 4: {
        if (tag == 32) {
         parse_type:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::apollo::perception::DAGConfig_SubnodeType_IsValid(value)) {
            set_type(static_cast< ::apollo::perception::DAGConfig_SubnodeType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(4, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.perception.DAGConfig.Subnode)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.perception.DAGConfig.Subnode)
  return false;
#undef DO_
}

void DAGConfig_Subnode::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.perception.DAGConfig.Subnode)
  // required int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // required string name = 2;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  // optional string reserve = 3;
  if (has_reserve()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->reserve().data(), this->reserve().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "reserve");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->reserve(), output);
  }

  // optional .apollo.perception.DAGConfig.SubnodeType type = 4 [default = SUBNODE_NORMAL];
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->type(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.perception.DAGConfig.Subnode)
}

::google::protobuf::uint8* DAGConfig_Subnode::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.perception.DAGConfig.Subnode)
  // required int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // required string name = 2;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  // optional string reserve = 3;
  if (has_reserve()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->reserve().data(), this->reserve().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "reserve");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->reserve(), target);
  }

  // optional .apollo.perception.DAGConfig.SubnodeType type = 4 [default = SUBNODE_NORMAL];
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      4, this->type(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.perception.DAGConfig.Subnode)
  return target;
}

int DAGConfig_Subnode::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // required string name = 2;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional string reserve = 3;
    if (has_reserve()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->reserve());
    }

    // optional .apollo.perception.DAGConfig.SubnodeType type = 4 [default = SUBNODE_NORMAL];
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DAGConfig_Subnode::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DAGConfig_Subnode* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DAGConfig_Subnode*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DAGConfig_Subnode::MergeFrom(const DAGConfig_Subnode& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_reserve()) {
      set_reserve(from.reserve());
    }
    if (from.has_type()) {
      set_type(from.type());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DAGConfig_Subnode::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DAGConfig_Subnode::CopyFrom(const DAGConfig_Subnode& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DAGConfig_Subnode::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void DAGConfig_Subnode::Swap(DAGConfig_Subnode* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(name_, other->name_);
    std::swap(reserve_, other->reserve_);
    std::swap(type_, other->type_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DAGConfig_Subnode::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DAGConfig_Subnode_descriptor_;
  metadata.reflection = DAGConfig_Subnode_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int DAGConfig_SubnodeConfig::kSubnodesFieldNumber;
#endif  // !_MSC_VER

DAGConfig_SubnodeConfig::DAGConfig_SubnodeConfig()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.perception.DAGConfig.SubnodeConfig)
}

void DAGConfig_SubnodeConfig::InitAsDefaultInstance() {
}

DAGConfig_SubnodeConfig::DAGConfig_SubnodeConfig(const DAGConfig_SubnodeConfig& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:apollo.perception.DAGConfig.SubnodeConfig)
}

void DAGConfig_SubnodeConfig::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DAGConfig_SubnodeConfig::~DAGConfig_SubnodeConfig() {
  // @@protoc_insertion_point(destructor:apollo.perception.DAGConfig.SubnodeConfig)
  SharedDtor();
}

void DAGConfig_SubnodeConfig::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DAGConfig_SubnodeConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DAGConfig_SubnodeConfig::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DAGConfig_SubnodeConfig_descriptor_;
}

const DAGConfig_SubnodeConfig& DAGConfig_SubnodeConfig::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dag_5fconfig_2eproto();
  return *default_instance_;
}

DAGConfig_SubnodeConfig* DAGConfig_SubnodeConfig::default_instance_ = NULL;

DAGConfig_SubnodeConfig* DAGConfig_SubnodeConfig::New() const {
  return new DAGConfig_SubnodeConfig;
}

void DAGConfig_SubnodeConfig::Clear() {
  subnodes_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DAGConfig_SubnodeConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.perception.DAGConfig.SubnodeConfig)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .apollo.perception.DAGConfig.Subnode subnodes = 1;
      case 1: {
        if (tag == 10) {
         parse_subnodes:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_subnodes()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_subnodes;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.perception.DAGConfig.SubnodeConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.perception.DAGConfig.SubnodeConfig)
  return false;
#undef DO_
}

void DAGConfig_SubnodeConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.perception.DAGConfig.SubnodeConfig)
  // repeated .apollo.perception.DAGConfig.Subnode subnodes = 1;
  for (int i = 0; i < this->subnodes_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->subnodes(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.perception.DAGConfig.SubnodeConfig)
}

::google::protobuf::uint8* DAGConfig_SubnodeConfig::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.perception.DAGConfig.SubnodeConfig)
  // repeated .apollo.perception.DAGConfig.Subnode subnodes = 1;
  for (int i = 0; i < this->subnodes_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->subnodes(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.perception.DAGConfig.SubnodeConfig)
  return target;
}

int DAGConfig_SubnodeConfig::ByteSize() const {
  int total_size = 0;

  // repeated .apollo.perception.DAGConfig.Subnode subnodes = 1;
  total_size += 1 * this->subnodes_size();
  for (int i = 0; i < this->subnodes_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->subnodes(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DAGConfig_SubnodeConfig::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DAGConfig_SubnodeConfig* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DAGConfig_SubnodeConfig*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DAGConfig_SubnodeConfig::MergeFrom(const DAGConfig_SubnodeConfig& from) {
  GOOGLE_CHECK_NE(&from, this);
  subnodes_.MergeFrom(from.subnodes_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DAGConfig_SubnodeConfig::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DAGConfig_SubnodeConfig::CopyFrom(const DAGConfig_SubnodeConfig& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DAGConfig_SubnodeConfig::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->subnodes())) return false;
  return true;
}

void DAGConfig_SubnodeConfig::Swap(DAGConfig_SubnodeConfig* other) {
  if (other != this) {
    subnodes_.Swap(&other->subnodes_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DAGConfig_SubnodeConfig::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DAGConfig_SubnodeConfig_descriptor_;
  metadata.reflection = DAGConfig_SubnodeConfig_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int DAGConfig_Event::kIdFieldNumber;
const int DAGConfig_Event::kNameFieldNumber;
#endif  // !_MSC_VER

DAGConfig_Event::DAGConfig_Event()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.perception.DAGConfig.Event)
}

void DAGConfig_Event::InitAsDefaultInstance() {
}

DAGConfig_Event::DAGConfig_Event(const DAGConfig_Event& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:apollo.perception.DAGConfig.Event)
}

void DAGConfig_Event::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DAGConfig_Event::~DAGConfig_Event() {
  // @@protoc_insertion_point(destructor:apollo.perception.DAGConfig.Event)
  SharedDtor();
}

void DAGConfig_Event::SharedDtor() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void DAGConfig_Event::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DAGConfig_Event::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DAGConfig_Event_descriptor_;
}

const DAGConfig_Event& DAGConfig_Event::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dag_5fconfig_2eproto();
  return *default_instance_;
}

DAGConfig_Event* DAGConfig_Event::default_instance_ = NULL;

DAGConfig_Event* DAGConfig_Event::New() const {
  return new DAGConfig_Event;
}

void DAGConfig_Event::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    id_ = 0;
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        name_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DAGConfig_Event::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.perception.DAGConfig.Event)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_name;
        break;
      }

      // optional string name = 2;
      case 2: {
        if (tag == 18) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.perception.DAGConfig.Event)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.perception.DAGConfig.Event)
  return false;
#undef DO_
}

void DAGConfig_Event::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.perception.DAGConfig.Event)
  // required int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // optional string name = 2;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.perception.DAGConfig.Event)
}

::google::protobuf::uint8* DAGConfig_Event::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.perception.DAGConfig.Event)
  // required int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // optional string name = 2;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.perception.DAGConfig.Event)
  return target;
}

int DAGConfig_Event::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // optional string name = 2;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DAGConfig_Event::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DAGConfig_Event* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DAGConfig_Event*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DAGConfig_Event::MergeFrom(const DAGConfig_Event& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_name()) {
      set_name(from.name());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DAGConfig_Event::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DAGConfig_Event::CopyFrom(const DAGConfig_Event& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DAGConfig_Event::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void DAGConfig_Event::Swap(DAGConfig_Event* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(name_, other->name_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DAGConfig_Event::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DAGConfig_Event_descriptor_;
  metadata.reflection = DAGConfig_Event_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int DAGConfig_Edge::kIdFieldNumber;
const int DAGConfig_Edge::kFromNodeFieldNumber;
const int DAGConfig_Edge::kToNodeFieldNumber;
const int DAGConfig_Edge::kEventsFieldNumber;
#endif  // !_MSC_VER

DAGConfig_Edge::DAGConfig_Edge()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.perception.DAGConfig.Edge)
}

void DAGConfig_Edge::InitAsDefaultInstance() {
}

DAGConfig_Edge::DAGConfig_Edge(const DAGConfig_Edge& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:apollo.perception.DAGConfig.Edge)
}

void DAGConfig_Edge::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0;
  from_node_ = 0;
  to_node_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DAGConfig_Edge::~DAGConfig_Edge() {
  // @@protoc_insertion_point(destructor:apollo.perception.DAGConfig.Edge)
  SharedDtor();
}

void DAGConfig_Edge::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DAGConfig_Edge::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DAGConfig_Edge::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DAGConfig_Edge_descriptor_;
}

const DAGConfig_Edge& DAGConfig_Edge::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dag_5fconfig_2eproto();
  return *default_instance_;
}

DAGConfig_Edge* DAGConfig_Edge::default_instance_ = NULL;

DAGConfig_Edge* DAGConfig_Edge::New() const {
  return new DAGConfig_Edge;
}

void DAGConfig_Edge::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<DAGConfig_Edge*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 7) {
    ZR_(id_, from_node_);
    to_node_ = 0;
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  events_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DAGConfig_Edge::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.perception.DAGConfig.Edge)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_from_node;
        break;
      }

      // required int32 from_node = 2;
      case 2: {
        if (tag == 16) {
         parse_from_node:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &from_node_)));
          set_has_from_node();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_to_node;
        break;
      }

      // required int32 to_node = 3;
      case 3: {
        if (tag == 24) {
         parse_to_node:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &to_node_)));
          set_has_to_node();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_events;
        break;
      }

      // repeated .apollo.perception.DAGConfig.Event events = 4;
      case 4: {
        if (tag == 34) {
         parse_events:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_events()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_events;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.perception.DAGConfig.Edge)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.perception.DAGConfig.Edge)
  return false;
#undef DO_
}

void DAGConfig_Edge::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.perception.DAGConfig.Edge)
  // required int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // required int32 from_node = 2;
  if (has_from_node()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->from_node(), output);
  }

  // required int32 to_node = 3;
  if (has_to_node()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->to_node(), output);
  }

  // repeated .apollo.perception.DAGConfig.Event events = 4;
  for (int i = 0; i < this->events_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->events(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.perception.DAGConfig.Edge)
}

::google::protobuf::uint8* DAGConfig_Edge::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.perception.DAGConfig.Edge)
  // required int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // required int32 from_node = 2;
  if (has_from_node()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->from_node(), target);
  }

  // required int32 to_node = 3;
  if (has_to_node()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->to_node(), target);
  }

  // repeated .apollo.perception.DAGConfig.Event events = 4;
  for (int i = 0; i < this->events_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->events(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.perception.DAGConfig.Edge)
  return target;
}

int DAGConfig_Edge::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // required int32 from_node = 2;
    if (has_from_node()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->from_node());
    }

    // required int32 to_node = 3;
    if (has_to_node()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->to_node());
    }

  }
  // repeated .apollo.perception.DAGConfig.Event events = 4;
  total_size += 1 * this->events_size();
  for (int i = 0; i < this->events_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->events(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DAGConfig_Edge::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DAGConfig_Edge* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DAGConfig_Edge*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DAGConfig_Edge::MergeFrom(const DAGConfig_Edge& from) {
  GOOGLE_CHECK_NE(&from, this);
  events_.MergeFrom(from.events_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_from_node()) {
      set_from_node(from.from_node());
    }
    if (from.has_to_node()) {
      set_to_node(from.to_node());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DAGConfig_Edge::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DAGConfig_Edge::CopyFrom(const DAGConfig_Edge& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DAGConfig_Edge::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->events())) return false;
  return true;
}

void DAGConfig_Edge::Swap(DAGConfig_Edge* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(from_node_, other->from_node_);
    std::swap(to_node_, other->to_node_);
    events_.Swap(&other->events_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DAGConfig_Edge::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DAGConfig_Edge_descriptor_;
  metadata.reflection = DAGConfig_Edge_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int DAGConfig_EdgeConfig::kEdgesFieldNumber;
#endif  // !_MSC_VER

DAGConfig_EdgeConfig::DAGConfig_EdgeConfig()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.perception.DAGConfig.EdgeConfig)
}

void DAGConfig_EdgeConfig::InitAsDefaultInstance() {
}

DAGConfig_EdgeConfig::DAGConfig_EdgeConfig(const DAGConfig_EdgeConfig& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:apollo.perception.DAGConfig.EdgeConfig)
}

void DAGConfig_EdgeConfig::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DAGConfig_EdgeConfig::~DAGConfig_EdgeConfig() {
  // @@protoc_insertion_point(destructor:apollo.perception.DAGConfig.EdgeConfig)
  SharedDtor();
}

void DAGConfig_EdgeConfig::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DAGConfig_EdgeConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DAGConfig_EdgeConfig::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DAGConfig_EdgeConfig_descriptor_;
}

const DAGConfig_EdgeConfig& DAGConfig_EdgeConfig::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dag_5fconfig_2eproto();
  return *default_instance_;
}

DAGConfig_EdgeConfig* DAGConfig_EdgeConfig::default_instance_ = NULL;

DAGConfig_EdgeConfig* DAGConfig_EdgeConfig::New() const {
  return new DAGConfig_EdgeConfig;
}

void DAGConfig_EdgeConfig::Clear() {
  edges_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DAGConfig_EdgeConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.perception.DAGConfig.EdgeConfig)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .apollo.perception.DAGConfig.Edge edges = 1;
      case 1: {
        if (tag == 10) {
         parse_edges:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_edges()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_edges;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.perception.DAGConfig.EdgeConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.perception.DAGConfig.EdgeConfig)
  return false;
#undef DO_
}

void DAGConfig_EdgeConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.perception.DAGConfig.EdgeConfig)
  // repeated .apollo.perception.DAGConfig.Edge edges = 1;
  for (int i = 0; i < this->edges_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->edges(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.perception.DAGConfig.EdgeConfig)
}

::google::protobuf::uint8* DAGConfig_EdgeConfig::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.perception.DAGConfig.EdgeConfig)
  // repeated .apollo.perception.DAGConfig.Edge edges = 1;
  for (int i = 0; i < this->edges_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->edges(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.perception.DAGConfig.EdgeConfig)
  return target;
}

int DAGConfig_EdgeConfig::ByteSize() const {
  int total_size = 0;

  // repeated .apollo.perception.DAGConfig.Edge edges = 1;
  total_size += 1 * this->edges_size();
  for (int i = 0; i < this->edges_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->edges(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DAGConfig_EdgeConfig::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DAGConfig_EdgeConfig* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DAGConfig_EdgeConfig*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DAGConfig_EdgeConfig::MergeFrom(const DAGConfig_EdgeConfig& from) {
  GOOGLE_CHECK_NE(&from, this);
  edges_.MergeFrom(from.edges_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DAGConfig_EdgeConfig::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DAGConfig_EdgeConfig::CopyFrom(const DAGConfig_EdgeConfig& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DAGConfig_EdgeConfig::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->edges())) return false;
  return true;
}

void DAGConfig_EdgeConfig::Swap(DAGConfig_EdgeConfig* other) {
  if (other != this) {
    edges_.Swap(&other->edges_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DAGConfig_EdgeConfig::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DAGConfig_EdgeConfig_descriptor_;
  metadata.reflection = DAGConfig_EdgeConfig_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int DAGConfig_SharedData::kIdFieldNumber;
const int DAGConfig_SharedData::kNameFieldNumber;
#endif  // !_MSC_VER

DAGConfig_SharedData::DAGConfig_SharedData()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.perception.DAGConfig.SharedData)
}

void DAGConfig_SharedData::InitAsDefaultInstance() {
}

DAGConfig_SharedData::DAGConfig_SharedData(const DAGConfig_SharedData& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:apollo.perception.DAGConfig.SharedData)
}

void DAGConfig_SharedData::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DAGConfig_SharedData::~DAGConfig_SharedData() {
  // @@protoc_insertion_point(destructor:apollo.perception.DAGConfig.SharedData)
  SharedDtor();
}

void DAGConfig_SharedData::SharedDtor() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void DAGConfig_SharedData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DAGConfig_SharedData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DAGConfig_SharedData_descriptor_;
}

const DAGConfig_SharedData& DAGConfig_SharedData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dag_5fconfig_2eproto();
  return *default_instance_;
}

DAGConfig_SharedData* DAGConfig_SharedData::default_instance_ = NULL;

DAGConfig_SharedData* DAGConfig_SharedData::New() const {
  return new DAGConfig_SharedData;
}

void DAGConfig_SharedData::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    id_ = 0;
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        name_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DAGConfig_SharedData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.perception.DAGConfig.SharedData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_name;
        break;
      }

      // required string name = 2;
      case 2: {
        if (tag == 18) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.perception.DAGConfig.SharedData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.perception.DAGConfig.SharedData)
  return false;
#undef DO_
}

void DAGConfig_SharedData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.perception.DAGConfig.SharedData)
  // required int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // required string name = 2;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.perception.DAGConfig.SharedData)
}

::google::protobuf::uint8* DAGConfig_SharedData::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.perception.DAGConfig.SharedData)
  // required int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // required string name = 2;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.perception.DAGConfig.SharedData)
  return target;
}

int DAGConfig_SharedData::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // required string name = 2;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DAGConfig_SharedData::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DAGConfig_SharedData* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DAGConfig_SharedData*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DAGConfig_SharedData::MergeFrom(const DAGConfig_SharedData& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_name()) {
      set_name(from.name());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DAGConfig_SharedData::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DAGConfig_SharedData::CopyFrom(const DAGConfig_SharedData& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DAGConfig_SharedData::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void DAGConfig_SharedData::Swap(DAGConfig_SharedData* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(name_, other->name_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DAGConfig_SharedData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DAGConfig_SharedData_descriptor_;
  metadata.reflection = DAGConfig_SharedData_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int DAGConfig_SharedDataConfig::kDatasFieldNumber;
#endif  // !_MSC_VER

DAGConfig_SharedDataConfig::DAGConfig_SharedDataConfig()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.perception.DAGConfig.SharedDataConfig)
}

void DAGConfig_SharedDataConfig::InitAsDefaultInstance() {
}

DAGConfig_SharedDataConfig::DAGConfig_SharedDataConfig(const DAGConfig_SharedDataConfig& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:apollo.perception.DAGConfig.SharedDataConfig)
}

void DAGConfig_SharedDataConfig::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DAGConfig_SharedDataConfig::~DAGConfig_SharedDataConfig() {
  // @@protoc_insertion_point(destructor:apollo.perception.DAGConfig.SharedDataConfig)
  SharedDtor();
}

void DAGConfig_SharedDataConfig::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DAGConfig_SharedDataConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DAGConfig_SharedDataConfig::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DAGConfig_SharedDataConfig_descriptor_;
}

const DAGConfig_SharedDataConfig& DAGConfig_SharedDataConfig::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dag_5fconfig_2eproto();
  return *default_instance_;
}

DAGConfig_SharedDataConfig* DAGConfig_SharedDataConfig::default_instance_ = NULL;

DAGConfig_SharedDataConfig* DAGConfig_SharedDataConfig::New() const {
  return new DAGConfig_SharedDataConfig;
}

void DAGConfig_SharedDataConfig::Clear() {
  datas_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DAGConfig_SharedDataConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.perception.DAGConfig.SharedDataConfig)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .apollo.perception.DAGConfig.SharedData datas = 1;
      case 1: {
        if (tag == 10) {
         parse_datas:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_datas()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_datas;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.perception.DAGConfig.SharedDataConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.perception.DAGConfig.SharedDataConfig)
  return false;
#undef DO_
}

void DAGConfig_SharedDataConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.perception.DAGConfig.SharedDataConfig)
  // repeated .apollo.perception.DAGConfig.SharedData datas = 1;
  for (int i = 0; i < this->datas_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->datas(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.perception.DAGConfig.SharedDataConfig)
}

::google::protobuf::uint8* DAGConfig_SharedDataConfig::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.perception.DAGConfig.SharedDataConfig)
  // repeated .apollo.perception.DAGConfig.SharedData datas = 1;
  for (int i = 0; i < this->datas_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->datas(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.perception.DAGConfig.SharedDataConfig)
  return target;
}

int DAGConfig_SharedDataConfig::ByteSize() const {
  int total_size = 0;

  // repeated .apollo.perception.DAGConfig.SharedData datas = 1;
  total_size += 1 * this->datas_size();
  for (int i = 0; i < this->datas_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->datas(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DAGConfig_SharedDataConfig::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DAGConfig_SharedDataConfig* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DAGConfig_SharedDataConfig*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DAGConfig_SharedDataConfig::MergeFrom(const DAGConfig_SharedDataConfig& from) {
  GOOGLE_CHECK_NE(&from, this);
  datas_.MergeFrom(from.datas_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DAGConfig_SharedDataConfig::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DAGConfig_SharedDataConfig::CopyFrom(const DAGConfig_SharedDataConfig& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DAGConfig_SharedDataConfig::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->datas())) return false;
  return true;
}

void DAGConfig_SharedDataConfig::Swap(DAGConfig_SharedDataConfig* other) {
  if (other != this) {
    datas_.Swap(&other->datas_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DAGConfig_SharedDataConfig::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DAGConfig_SharedDataConfig_descriptor_;
  metadata.reflection = DAGConfig_SharedDataConfig_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int DAGConfig::kSubnodeConfigFieldNumber;
const int DAGConfig::kEdgeConfigFieldNumber;
const int DAGConfig::kDataConfigFieldNumber;
#endif  // !_MSC_VER

DAGConfig::DAGConfig()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.perception.DAGConfig)
}

void DAGConfig::InitAsDefaultInstance() {
  subnode_config_ = const_cast< ::apollo::perception::DAGConfig_SubnodeConfig*>(&::apollo::perception::DAGConfig_SubnodeConfig::default_instance());
  edge_config_ = const_cast< ::apollo::perception::DAGConfig_EdgeConfig*>(&::apollo::perception::DAGConfig_EdgeConfig::default_instance());
  data_config_ = const_cast< ::apollo::perception::DAGConfig_SharedDataConfig*>(&::apollo::perception::DAGConfig_SharedDataConfig::default_instance());
}

DAGConfig::DAGConfig(const DAGConfig& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:apollo.perception.DAGConfig)
}

void DAGConfig::SharedCtor() {
  _cached_size_ = 0;
  subnode_config_ = NULL;
  edge_config_ = NULL;
  data_config_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DAGConfig::~DAGConfig() {
  // @@protoc_insertion_point(destructor:apollo.perception.DAGConfig)
  SharedDtor();
}

void DAGConfig::SharedDtor() {
  if (this != default_instance_) {
    delete subnode_config_;
    delete edge_config_;
    delete data_config_;
  }
}

void DAGConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DAGConfig::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DAGConfig_descriptor_;
}

const DAGConfig& DAGConfig::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dag_5fconfig_2eproto();
  return *default_instance_;
}

DAGConfig* DAGConfig::default_instance_ = NULL;

DAGConfig* DAGConfig::New() const {
  return new DAGConfig;
}

void DAGConfig::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_subnode_config()) {
      if (subnode_config_ != NULL) subnode_config_->::apollo::perception::DAGConfig_SubnodeConfig::Clear();
    }
    if (has_edge_config()) {
      if (edge_config_ != NULL) edge_config_->::apollo::perception::DAGConfig_EdgeConfig::Clear();
    }
    if (has_data_config()) {
      if (data_config_ != NULL) data_config_->::apollo::perception::DAGConfig_SharedDataConfig::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DAGConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.perception.DAGConfig)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .apollo.perception.DAGConfig.SubnodeConfig subnode_config = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_subnode_config()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_edge_config;
        break;
      }

      // required .apollo.perception.DAGConfig.EdgeConfig edge_config = 2;
      case 2: {
        if (tag == 18) {
         parse_edge_config:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_edge_config()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_data_config;
        break;
      }

      // required .apollo.perception.DAGConfig.SharedDataConfig data_config = 3;
      case 3: {
        if (tag == 26) {
         parse_data_config:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_data_config()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.perception.DAGConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.perception.DAGConfig)
  return false;
#undef DO_
}

void DAGConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.perception.DAGConfig)
  // required .apollo.perception.DAGConfig.SubnodeConfig subnode_config = 1;
  if (has_subnode_config()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->subnode_config(), output);
  }

  // required .apollo.perception.DAGConfig.EdgeConfig edge_config = 2;
  if (has_edge_config()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->edge_config(), output);
  }

  // required .apollo.perception.DAGConfig.SharedDataConfig data_config = 3;
  if (has_data_config()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->data_config(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.perception.DAGConfig)
}

::google::protobuf::uint8* DAGConfig::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.perception.DAGConfig)
  // required .apollo.perception.DAGConfig.SubnodeConfig subnode_config = 1;
  if (has_subnode_config()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->subnode_config(), target);
  }

  // required .apollo.perception.DAGConfig.EdgeConfig edge_config = 2;
  if (has_edge_config()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->edge_config(), target);
  }

  // required .apollo.perception.DAGConfig.SharedDataConfig data_config = 3;
  if (has_data_config()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->data_config(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.perception.DAGConfig)
  return target;
}

int DAGConfig::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .apollo.perception.DAGConfig.SubnodeConfig subnode_config = 1;
    if (has_subnode_config()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->subnode_config());
    }

    // required .apollo.perception.DAGConfig.EdgeConfig edge_config = 2;
    if (has_edge_config()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->edge_config());
    }

    // required .apollo.perception.DAGConfig.SharedDataConfig data_config = 3;
    if (has_data_config()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->data_config());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DAGConfig::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DAGConfig* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DAGConfig*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DAGConfig::MergeFrom(const DAGConfig& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_subnode_config()) {
      mutable_subnode_config()->::apollo::perception::DAGConfig_SubnodeConfig::MergeFrom(from.subnode_config());
    }
    if (from.has_edge_config()) {
      mutable_edge_config()->::apollo::perception::DAGConfig_EdgeConfig::MergeFrom(from.edge_config());
    }
    if (from.has_data_config()) {
      mutable_data_config()->::apollo::perception::DAGConfig_SharedDataConfig::MergeFrom(from.data_config());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DAGConfig::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DAGConfig::CopyFrom(const DAGConfig& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DAGConfig::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  if (has_subnode_config()) {
    if (!this->subnode_config().IsInitialized()) return false;
  }
  if (has_edge_config()) {
    if (!this->edge_config().IsInitialized()) return false;
  }
  if (has_data_config()) {
    if (!this->data_config().IsInitialized()) return false;
  }
  return true;
}

void DAGConfig::Swap(DAGConfig* other) {
  if (other != this) {
    std::swap(subnode_config_, other->subnode_config_);
    std::swap(edge_config_, other->edge_config_);
    std::swap(data_config_, other->data_config_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DAGConfig::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DAGConfig_descriptor_;
  metadata.reflection = DAGConfig_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace perception
}  // namespace apollo

// @@protoc_insertion_point(global_scope)
